<!--#include file="../Include/Conn.asp" -->
<!--#include file="../Include/inc.asp" -->
<!--#include file="seeion.asp"-->
<%call chkAdmin(34)%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312" />
<link rel="stylesheet" href="images/style.css">
<%
Session("count") = 0
strURL = "http://" & request.servervariables("server_name")&""
Dim foolcat
foolcat = foolcat + "<?xml version=""1.0"" encoding=""utf-8""?>"&vbcrlf
foolcat = foolcat + "<!--Google Site Map File Generated by http://www.shgwzy.com SiteMap Time: " & return_RFC822_Date(Now, "GMT") & "-->"&vbcrlf
foolcat = foolcat + "<urlset xmlns=""http://www.google.com/schemas/sitemap/0.84"">"&vbcrlf
foolcat = foolcat + "<url>"&vbcrlf
foolcat = foolcat + "<loc>" & strURL & "</loc>"&vbcrlf
foolcat = foolcat + "<lastmod>" & FormatTime(Now, 1) & "</lastmod>"&vbcrlf
foolcat = foolcat + "<changefreq>always</changefreq>"&vbcrlf
foolcat = foolcat + "<priority>1.0</priority>"&vbcrlf
foolcat = foolcat + "</url>"&vbcrlf
foolcat = foolcat + "<url>"&vbcrlf
foolcat = foolcat + "<loc>" & strURL & ""&dir&"Case/</loc>"&vbcrlf
foolcat = foolcat + "<lastmod>" & FormatTime(Now, 1) & "</lastmod>"&vbcrlf
foolcat = foolcat + "<changefreq>always</changefreq>"&vbcrlf
foolcat = foolcat + "<priority>1.0</priority>"&vbcrlf
foolcat = foolcat + "</url>"&vbcrlf
foolcat = foolcat + "<url>"&vbcrlf
foolcat = foolcat + "<loc>" & strURL & ""&dir&"Download/</loc>"&vbcrlf
foolcat = foolcat + "<lastmod>" & FormatTime(Now, 1) & "</lastmod>"&vbcrlf
foolcat = foolcat + "<changefreq>always</changefreq>"&vbcrlf
foolcat = foolcat + "<priority>1.0</priority>"&vbcrlf
foolcat = foolcat + "</url>"&vbcrlf
Session("count") = Session("count") + "1"
Dim Rs, SQL
Set Rs = server.CreateObject("adodb.RecordSet")
SQL = "select * from News"
Set Rs = conn.Execute (SQL)
Do Until Rs.EOF
ID = rs("ID")
    If html = 0 Then
        AutoLink = "News/"&ShowNews&""&Separated&""&ID&"."&HTMLName&""
    Else
        AutoLink = "News/ShowNews.asp?ID="&Rs("ID")&""
    End If
    foolcat = foolcat + "<url>"&vbcrlf
    foolcat = foolcat + "<loc>" & strURL & ""&dir&"" & AutoLink & "</loc>"&vbcrlf
    foolcat = foolcat + "<lastmod>"&FormatTime(Rs("data"), 1)&"</lastmod>"&vbcrlf
    foolcat = foolcat + "<changefreq>daily</changefreq>"&vbcrlf
    foolcat = foolcat + "<priority>0.8</priority>"&vbcrlf
    foolcat = foolcat + "</url>"&vbcrlf
    Session("count") = Session("count") + "1"
    Rs.movenext
Loop
Rs.Close
Set Rs = Nothing

'产品分类
Set Rs = server.CreateObject("adodb.RecordSet")
SQL = "select * from bigClass"
Set Rs = conn.Execute (SQL)
Do Until Rs.EOF
ID = rs("BigClassID")
    If html = 0 Then
        AutoLink = "Products/"&Productsfl&""&Separated&""&ID&"."&HTMLName&""
    Else
        AutoLink = "Products/?BigClassID="&rs("BigClassID")&""
    End If
    foolcat = foolcat + "<url>"&vbcrlf
    foolcat = foolcat + "<loc>" & strURL & ""&dir&"" & AutoLink & "</loc>"&vbcrlf
    foolcat = foolcat + "<lastmod>"&FormatTime(Rs("data"), 1)&"</lastmod>"&vbcrlf
    foolcat = foolcat + "<changefreq>daily</changefreq>"&vbcrlf
    foolcat = foolcat + "<priority>0.8</priority>"&vbcrlf
    foolcat = foolcat + "</url>"&vbcrlf
    Session("count") = Session("count") + "1"
    Rs.movenext
Loop
Rs.Close
Set Rs = Nothing

'产品页面
Set Rs = server.CreateObject("adodb.RecordSet")
SQL = "select * from Products"
Set Rs = conn.Execute (SQL)
Do Until Rs.EOF
ID = rs("ID")
    If html = 0 Then
        AutoLink = "Products/"&ShowProducts&""&Separated&""&ID&"."&HTMLName&""
    Else
        AutoLink = "Products/ShowProducts.asp?ID="&rs("ID")&""
    End If
    foolcat = foolcat + "<url>"&vbcrlf
    foolcat = foolcat + "<loc>" & strURL & ""&dir&"" & AutoLink & "</loc>"&vbcrlf
    foolcat = foolcat + "<lastmod>"&FormatTime(Rs("data"), 1)&"</lastmod>"&vbcrlf
    foolcat = foolcat + "<changefreq>daily</changefreq>"&vbcrlf
    foolcat = foolcat + "<priority>0.8</priority>"&vbcrlf
    foolcat = foolcat + "</url>"&vbcrlf
    Session("count") = Session("count") + "1"
    Rs.movenext
Loop
Rs.Close
Set Rs = Nothing

Set Rs = server.CreateObject("adodb.RecordSet")
SQL = "select * from Download"
Set Rs = conn.Execute (SQL)
Do Until Rs.EOF
ID = rs("ID")
    If html = 0 Then
        AutoLink = "Download/"&ShowDownload&""&Separated&""&ID&"."&HTMLName&""
    Else
        AutoLink = "Download/ShowDownload.asp?ID="&rs("ID")&""
    End If
    foolcat = foolcat + "<url>"&vbcrlf
    foolcat = foolcat + "<loc>" & strURL & ""&dir&"" & AutoLink & "</loc>"&vbcrlf
    foolcat = foolcat + "<lastmod>"&FormatTime(Rs("data"), 1)&"</lastmod>"&vbcrlf
    foolcat = foolcat + "<changefreq>daily</changefreq>"&vbcrlf
    foolcat = foolcat + "<priority>0.6</priority>"&vbcrlf
    foolcat = foolcat + "</url>"&vbcrlf
    Session("count") = Session("count") + "1"
    Rs.movenext
Loop
Rs.Close
Set Rs = Nothing

Set Rs = server.CreateObject("adodb.RecordSet")
SQL = "select * from [case]"
Set Rs = conn.Execute (SQL)
Do Until Rs.EOF
ID = rs("ID")
    If html = 0 Then
        AutoLink = "Case/"&ShowCase&""&Separated&""&ID&"."&HTMLName&""
    Else
        AutoLink = "Case/ShowCase.asp?ID="&rs("ID")&""
    End If
    foolcat = foolcat + "<url>"&vbcrlf
    foolcat = foolcat + "<loc>" & strURL & ""&dir&"" & AutoLink & "</loc>"&vbcrlf
    foolcat = foolcat + "<lastmod>"&FormatTime(Rs("data"), 1)&"</lastmod>"&vbcrlf
    foolcat = foolcat + "<changefreq>daily</changefreq>"&vbcrlf
    foolcat = foolcat + "<priority>0.6</priority>"&vbcrlf
    foolcat = foolcat + "</url>"&vbcrlf
    Session("count") = Session("count") + "1"
    Rs.movenext
Loop
Rs.Close
Set Rs = Nothing

Set Rs = server.CreateObject("adodb.RecordSet")
SQL = "select * from About"
Set Rs = conn.Execute (SQL)
ID = rs("ID")
Do Until Rs.EOF
    If html = 0 Then
        AutoLink = "About/"&about&""&Separated&""&ID&"."&HTMLName&""
    Else
        AutoLink = "About/?ID="&rs("ID")&""
    End If
    foolcat = foolcat + "<url>"&vbcrlf
    foolcat = foolcat + "<loc>" & strURL & ""&dir&"" & AutoLink & "</loc>"&vbcrlf
    foolcat = foolcat + "<lastmod>"&FormatTime(Rs("data"), 1)&"</lastmod>"&vbcrlf
    foolcat = foolcat + "<changefreq>daily</changefreq>"&vbcrlf
    foolcat = foolcat + "<priority>0.5</priority>"&vbcrlf
    foolcat = foolcat + "</url>"&vbcrlf
    Session("count") = Session("count") + "1"
    Rs.movenext
Loop
Rs.Close
Set Rs = Nothing

Set Rs = server.CreateObject("adodb.RecordSet")
SQL = "select * from project"
Set Rs = conn.Execute (SQL)
Do Until Rs.EOF
ID = rs("ID")
    If html = 0 Then
        AutoLink = "Service/"&Showproject&""&Separated&""&ID&"."&HTMLName&""
    Else
        AutoLink = "Service/Showproject.asp?ID="&rs("ID")&""
    End If
    foolcat = foolcat + "<url>"&vbcrlf
    foolcat = foolcat + "<loc>" & strURL & ""&dir&"" & AutoLink & "</loc>"&vbcrlf
    foolcat = foolcat + "<lastmod>"&FormatTime(now(), 1)&"</lastmod>"&vbcrlf
    foolcat = foolcat + "<changefreq>daily</changefreq>"&vbcrlf
    foolcat = foolcat + "<priority>0.5</priority>"&vbcrlf
    foolcat = foolcat + "</url>"&vbcrlf
    Session("count") = Session("count") + "1"
    Rs.movenext
Loop
Rs.Close
Set Rs = Nothing

Set Rs = server.CreateObject("adodb.RecordSet")
SQL = "select * from tuandui"
Set Rs = conn.Execute (SQL)
Do Until Rs.EOF
ID = rs("ID")
    If html = 0 Then
        AutoLink = "team/"&Showteam&""&Separated&""&ID&"."&HTMLName&""
    Else
        AutoLink = "team/Showteam.asp?ID="&rs("ID")&""
    End If
    foolcat = foolcat + "<url>"&vbcrlf
    foolcat = foolcat + "<loc>" &strURL & ""&dir&"" & AutoLink & "</loc>"&vbcrlf
    foolcat = foolcat + "<lastmod>"&FormatTime(Rs("data"), 1)&"</lastmod>"&vbcrlf
    foolcat = foolcat + "<changefreq>daily</changefreq>"&vbcrlf
    foolcat = foolcat + "<priority>0.5</priority>"&vbcrlf
    foolcat = foolcat + "</url>"&vbcrlf
    Session("count") = Session("count") + "1"
    Rs.movenext
Loop
Rs.Close
Set Rs = Nothing

foolcat = foolcat + "</urlset>"&vbcrlf

foolcat = "" + foolcat + ""
foolcat = "" & foolcat & ""
FolderPath = Server.MapPath("..")
Set fso = Server.CreateObject("Scripting.FileSystemObject")
Set fout = fso.CreateTextFile(FolderPath&"\sitemap.xml")
fout.WriteLine foolcat
fout.Close
Set fout = Nothing
conn.Close
Set conn = Nothing

Function return_RFC822_Date(ByVal myDate, ByVal TimeZone)
    Dim myDay, myDays, myMonth, myYear
    Dim myHours, myMinutes, mySeconds

    myDate = CDate(myDate)
    myDay = EnWeekDayName(myDate)
    myDays = Right("00" & Day(myDate), 2)
    myMonth = EnMonthName(myDate)
    myYear = Year(myDate)
    myHours = Right("00" & Hour(myDate), 2)
    myMinutes = Right("00" & Minute(myDate), 2)
    mySeconds = Right("00" & Second(myDate), 2)

    return_RFC822_Date = myDay&", "& _
                         myDays&" "& _
                         myMonth&" "& _
                         myYear&" "& _
                         myHours&":"& _
                         myMinutes&":"& _
                         mySeconds&" "& _
                         " " & TimeZone
End Function

Function EnWeekDayName(InputDate)
    Dim Result
    Select Case Weekday(InputDate, 1)
        Case 1
            Result = "Sun"
        Case 2
            Result = "Mon"
        Case 3
            Result = "Tue"
        Case 4
            Result = "Wed"
        Case 5
            Result = "Thu"
        Case 6
            Result = "Fri"
        Case 7
            Result = "Sat"
    End Select
    EnWeekDayName = Result
End Function

Function EnMonthName(InputDate)
    Dim Result
    Select Case Month(InputDate)
        Case 1
            Result = "Jan"
        Case 2
            Result = "Feb"
        Case 3
            Result = "Mar"
        Case 4
            Result = "Apr"
        Case 5
            Result = "May"
        Case 6
            Result = "Jun"
        Case 7
            Result = "Jul"
        Case 8
            Result = "Aug"
        Case 9
            Result = "Sep"
        Case 10
            Result = "Oct"
        Case 11
            Result = "Nov"
        Case 12
            Result = "Dec"
    End Select
    EnMonthName = Result
End Function

Function FormatTime(sTime, iFmt)
    Dim sTemp
    If IsNull(sTime) Or sTime = "" Then
        FormatTime = Year(Date) & "-" & Right("0" & Month(Date), 2) & "-" & Right("0" & Day(Date), 2)
        Exit Function
    End If
    sTemp = Year(sTime) & "-" & Right("0" & Month(sTime), 2) & "-" & Right("0" & Day(sTime), 2)
    Select Case iFmt
        Case 0
            FormatTime = sTemp
        Case 1
            FormatTime = sTemp& "T" & Right("0" & Hour(sTime), 2) & ":" & Right("0" & Minute(sTime), 2) & "+08:00"
    End Select
End Function
Response.Write "<table width=""100%"" border=""0"" align=""center"" cellpadding=""0"" cellspacing=""1"" bgcolor=""#666666"">"
Response.Write "<tr>"
Response.Write "<td height=""30"" background=""images/bg_list.gif""><div  style=""padding-left:10px; font-weight:bold; color:#FFFFFF; text-align:left"">SiteMap生成</div></td>"
Response.Write "</tr>"
Response.Write "<tr>"
Response.Write "<td align=""center"" bgcolor=""#FFFFFF"">"
Response.Write "<div style=""line-height:28px"">高屋置业为您提供适用于baidu的SiteMap.xml文件生成完毕，共<font color=""#FF0000"">"&Session("count")&"</font>条记录被索引</div>"
Response.Write "<div style=""line-height:28px"">点击查看<a href=""../sitemap.xml"" target=""_blank""><font color=""#FF0000"">SiteMap.xml</font></a>"
Response.Write "<a href=""http://www.google.com/webmasters/sitemaps/"" target=""_blank"">立即提交至Google</a></div>"
Response.Write "</td>"
Response.Write "</tr>"
Response.Write "</table>"
%>