<%
Const html = 1  '------开启网站静态
Const HTMLdir = ""   '------网站静态目录
Const sy_dy_id = 1
Const sy_dy_zs = 530
Const HTMLName = "html"
Const Casefl = "Case"
Const ShowCase = "ShowCase"
Const Newsfl = "News"
Const ShowNews = "ShowNews"
Const Productsfl = "Products"
Const ShowProducts = "ShowProducts"
Const Videofl = "Video"
Const ShowVideo = "ShowVideo"
Const Downloadfl = "Download"
Const ShowDownload = "ShowDownload"
Const Planningfl = ""
Const ShowPlanning = ""
Const photofl = "photo"
Const Showphoto = "Showphoto"
Const Showteam = "show"
Const Showjob = "Showjob"
Const Showproject = "Service"
Const about = "about"
Const fy = "page"
Const Separated = "_"
Const body_no = 0
Const body_bj = "/uploadfile/image/photo/20150226234332003200_ZYCH.jpg"
Const body_color= "#999900"
Const link = 0
Const ditu_title= "上海高屋置业"
Const ditu_Coordinate= "121.459938,30.926897"
Const ditu_mc = "上海高屋置业有限公司"
Const ditu_sm = "上海高屋置业有限公司"
Const zych_weibo = ""
Const code = 0
Const userzc = 0
Const usersh = 0
Const qqkf = 1
Const Scroll = 1
Const in_title= "项目展示"
Const in_hs= "2"
Const newslb = "2"
Const vid_pay = "0"
Const vid_wz= ""
Const wap = "0"
Const zych_rwmon = "1"
Const zych_inpro = ""
Const zych_rwmurl = "/uploadfile/file/20150302172012781278_ZYCH.jpg"
Const Watermark = 1
Const Watermark_url = ""
Const Watermark_w = ""
Const Watermark_h = ""
Const pay= 1
Const alipayLX = "danbao"
Const alipayID = ""
Const alipayPID = ""
Const alipayKey = ""
Const kdappKey = ""
%>